package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.junit.Test;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {

    gotoGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("test 1", "test 2", "test 3"));
    submitGroupCreation();
    returnToGroupPage();
  }

}
