package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.stqa.pft.addressbook.model.ContactData;

public class ContactCreationTests extends TestBase {

    @Test
    public void testContactCreation() {
        app.getNavigationHelper().gotoHomePage();
        app.getNavigationHelper().initNewContact();
        app.getContactHelper().fillContactForm(new ContactData("test 1", "test 2", "test 1"), true);
        app.getContactHelper().submitContactCreation();
        app.getNavigationHelper().gotoHomePage();
    }
}
