package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.stqa.pft.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {

    app.gotoGroupPage();
    app.initGroupCreation();
    app.fillGroupForm(new GroupData("test 1", "test 2", "test 3"));
    app.submitGroupCreation();
    app.returnToGroupPage();
  }

}
